simucredito/urls.py
from django.conf.urls import patterns, include, url
from simucredito import views

urlpatterns = patterns('',
	
	url(r'^$', views.index, name='index'),
	url(r'^login_user/$', views.login_user, name='login_user'),
	url(r'^logout_user/(?P<admin_id>\d+)/$', views.logout_user, name='logout_user'),
	url(r'^autenticar/$', views.autenticar, name='autenticar'),
	url(r'^nuevo_administrador/', views.nuevo_administrador, name='nuevo_administrador'),
	url(r'^crear_administrador/', views.crear_administrador, name='crear_administrador'),
    
	url(r'^administradores/(?P<admin_id>\d+)/admin_menu/$', views.admin_menu, name='admin_menu'),
	url(r'^administradores/(?P<admin_id>\d+)/admin_credito/$', views.admin_credito, name='admin_credito'),
	url(r'^administradores/(?P<admin_id>\d+)/admin_credito/admin_credito_detalles/(?P<credito_id>\d+)/$', views.admin_credito_detalles, name='admin_credito_detalles'),
	url(r'^administradores/(?P<admin_id>\d+)/lineas_credito/$', views.lineas_credito, name='lineas_credito'),
    url(r'^administradores/(?P<admin_id>\d+)/nueva_linea_credito/$', views.nueva_linea_credito, name='nueva_linea_credito'),
    url(r'^administradores/(?P<admin_id>\d+)/crear_linea_credito/$', views.crear_linea_credito, name='crear_linea_credito'),
    url(r'^administradores/(?P<admin_id>\d+)/(?P<linea_credito_id>\d+)/linea_credito/$', views.linea_credito, name='linea_credito'),
    url(r'^administradores/(?P<admin_id>\d+)/(?P<linea_credito_id>\d+)/editar_linea_credito/$', views.editar_linea_credito, name='editar_linea_credito'),
	url(r'^administradores/(?P<admin_id>\d+)/(?P<linea_credito_id>\d+)/eliminar_linea_credito/$', views.eliminar_linea_credito, name='eliminar_linea_credito'),
	
	url(r'^zonaclientes/(?P<admin_id>\d+)/nuevo_credito/$', views.nuevo_credito, name='nuevo_credito'),
	url(r'^zonaclientes/(?P<admin_id>\d+)/crear_credito/$', views.crear_credito, name='crear_credito'),
	url(r'^zonaclientes/(?P<admin_id>\d+)/client_menu/$', views.client_menu, name='client_menu'),
	url(r'^zonaclientes/(?P<admin_id>\d+)/client_credito/(?P<client_id>\d+)/$', views.client_credito, name='client_credito'),
	url(r'^zonaclientes/(?P<admin_id>\d+)/buscar_credito/$', views.buscar_credito, name='buscar_credito'),
	url(r'^zonaclientes/(?P<admin_id>\d+)/client_credito/(?P<client_id>\d+)/client_credito_detalles/(?P<credito_id>\d+)/$', views.client_credito_detalles, name='client_credito_detalles'),
)

simuladoresdecredito/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from simucredito import views

urlpatterns = patterns('',
    url(r'^simucredito/', include('simucredito.urls', namespace="simucredito")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hirefire/cba66b54db4b18c2c5e1ef8d391b9a9d3e3d4ba6/info', views.sqs, name='sqs'),
)

simucredito/models.py
from datetime import date, datetime

from decimal import Decimal
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

class DocumentType(models.Model):
    nombre = models.CharField(max_length=50)
    nombre_corto = models.CharField(max_length=3)

    def __str__(self):
        return self.nombre_corto

class CreditType(models.Model):
    tipo = models.CharField(max_length=50)
    cuotas_maximas = models.PositiveIntegerField(validators=[MinValueValidator(6), MaxValueValidator(120)])
    
    def __str__(self):
        return self.tipo

class CreditStatus(models.Model):
	id_estado = models.PositiveIntegerField(validators=[MinValueValidator(0), MaxValueValidator(50)])
	nombre = models.CharField(max_length=50)
	def __str__(self):
		return self.nombre
		
class Administrator(models.Model):
    numero_documento = models.CharField(max_length=20)
    tipo_documento = models.ForeignKey(DocumentType)
    nombres = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200)
    email = models.EmailField(max_length=50, blank=True, null=True, unique=True)
    url = models.CharField(max_length=500)
	
    def __str__(self):
        return self.numero_documento + " - " + self.nombres + " " + self.apellidos
 
class CreditLine(models.Model):
	administrador = models.ForeignKey(Administrator)
	tipo = models.ForeignKey(CreditType)
	tasa_interes = models.DecimalField(max_digits=3, decimal_places=1)
	fecha_creacion = models.DateField(auto_now_add=True)
	fecha_modificacion = models.DateField(auto_now=True)
	
	def __str__(self):
		return self.tipo.tipo

class Client(models.Model):
    numero_documento = models.CharField(max_length=20)
    tipo_documento = models.ForeignKey(DocumentType)
    nombres = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200)
    fecha_nacimiento = models.DateTimeField()
    
    def __str__(self):
        return self.numero_documento + " - " + self.nombres + " " + self.apellidos

class Credit(models.Model):
	cliente = models.ForeignKey(Client)
	administrador = models.ForeignKey(Administrator)
	estado = models.ForeignKey(CreditStatus)
	linea_credito = models.ForeignKey(CreditLine)
	tasa_interes = models.DecimalField(max_digits=3, decimal_places=1)
	valor = models.DecimalField(max_digits=20, decimal_places=1)
	cuotas = models.DecimalField(max_digits=20, decimal_places=1)
	nivel_riesgo = models.DecimalField(max_digits=20, decimal_places=1, default=Decimal(-10.0))
	fecha_creacion = models.DateField(auto_now_add=True)
	
	def __str__(self):
		return self.cliente.nombres + " " + self.cliente.apellidos + " - " + self.linea_credito.tipo.tipo

	def get_riesgo(self):
		if self.nivel_riesgo == -10:
			return "No disponible"
		else:
			return self.nivel_riesgo

class PaymentPlan(models.Model):
	cliente = models.ForeignKey(Client)
	credito = models.ForeignKey(Credit)
	cuota = models.PositiveIntegerField(validators=[MinValueValidator(0), MaxValueValidator(120)])
	abono_capital = models.DecimalField(max_digits=10, decimal_places=1)
	interes = models.DecimalField(max_digits=10, decimal_places=1)
	cuota_mensual = models.DecimalField(max_digits=10, decimal_places=1)
	saldo = models.DecimalField(max_digits=10, decimal_places=1)
	
	def __str__(self):
		return self.cliente.nombres + " " + self.cliente.apellidos

simucredito/views.py
import datetime

from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages 
from django.utils import timezone

from simucredito.mongodb_models.document_type import DocumentTypes, DocumentType
from simucredito.mongodb_models.administrator import Administrator
from simucredito.mongodb_models.credit_type import CreditTypes, CreditType
from simucredito.mongodb_models.credit_line import CreditLine
from simucredito.mongodb_models.client import Client
from simucredito.mongodb_models.credit import Credit
from boto.sqs.connection import SQSConnection
from simucredito.session import Session
from django.core.cache import cache

"""Views for anonymous"""
def index(request):
	return render(request, "simucredito/index.html")

def sqs(request):
	conn = SQSConnection(is_secure=False, validate_certs=False, debug=1, aws_access_key_id="AKIAI4SUVO4QA3OOCYJA" , aws_secret_access_key="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")
	credits_queue = conn.get_queue('Creditos_Queue')
	queue_count = credits_queue.count()
	return render(request, "simucredito/sqs.html", {
		"queue_count" : queue_count
		})

def nuevo_administrador(request):
	return render(request, "simucredito/nuevo_administrador.html", {
		"document_types": DocumentTypes()
		})

def crear_administrador(request):
	administrador = Administrator()
	administrador.create(
		tipo_documento = request.POST["tipo_documento"],
		numero_documento = request.POST["numero_documento"],
		nombres = request.POST["nombres"],
		apellidos = request.POST["apellidos"],
		email = request.POST["email"],
		)
	return HttpResponseRedirect(reverse('simucredito:login_user'))

def login_user(request):
	return render(request, "simucredito/login.html")

def autenticar(request):
	administrador = Administrator()
	try:
		id = administrador.get_id_by_email(request.POST["usuario"])
		print "El id del usuario es " + id
		Session().login(id)
		return HttpResponseRedirect(reverse('simucredito:admin_menu', args=(id,)))
	except:
		return HttpResponseRedirect(reverse('simucredito:login_user'))

def logout_user(request, admin_id):
	Session().logout(admin_id)
	return HttpResponseRedirect(reverse('simucredito:login_user'))

"""Views for administrators"""
def admin_menu(request, admin_id):
	if not Session().verify(admin_id):
		return HttpResponseRedirect(reverse('simucredito:login_user'))
	else:
		administrator = Administrator()
		administrator.load(admin_id)
		return render(request, "simucredito/admin_menu.html", 
			{
			"administrator": administrator,
			})
		
def lineas_credito(request, admin_id):
	if not Session().verify(admin_id):
		return HttpResponseRedirect(reverse('simucredito:login_user'))
	administrator = Administrator()
	administrator.load(admin_id)
	return render(request, "simucredito/lineas_credito.html", 
		{
			"administrator": administrator
		})

def linea_credito(request, admin_id, linea_credito_id):
	if not Session().verify(admin_id):
		return HttpResponseRedirect(reverse('simucredito:login_user'))
	administrator = Administrator()
	administrator.load(admin_id)
	linea_credito = CreditLine()
	linea_credito.load(linea_credito_id)
	return render(request, "simucredito/linea_credito.html", {
		"administrator": administrator,
		"linea_credito": linea_credito
		})

def nueva_linea_credito(request, admin_id):
	if not Session().verify(admin_id):
		return HttpResponseRedirect(reverse('simucredito:login_user'))
	administrator = Administrator()
	administrator.load(admin_id)
	return render(request, "simucredito/nueva_linea_credito.html", {
		"administrator": administrator,
		"credittypes": CreditTypes
		})

def crear_linea_credito(request, admin_id):
	if not Session().verify(admin_id):
		return HttpResponseRedirect(reverse('simucredito:login_user'))
	credit_type = CreditType()
	credit_type.load(request.POST["creditline"])
	creditline = CreditLine()
	creditline.create(admin_id, credit_type.tipo, credit_type.cuotas_maximas, request.POST["tasa_interes"])
	return HttpResponseRedirect(reverse('simucredito:lineas_credito', args=(admin_id,)))

def editar_linea_credito(request, admin_id, linea_credito_id):
	if not Session().verify(admin_id):
		return HttpResponseRedirect(reverse('simucredito:login_user'))
	linea_credito = CreditLine()
	linea_credito.load(linea_credito_id)
	linea_credito.tasa_interes = request.POST["tasa_interes"]
	linea_credito.fecha_modificacion = str(datetime.datetime.now())
	linea_credito.save()
	return HttpResponseRedirect(reverse('simucredito:lineas_credito', args=(admin_id,)))

def eliminar_linea_credito(request, admin_id, linea_credito_id):
	if not Session().verify(admin_id):
		return HttpResponseRedirect(reverse('simucredito:login_user'))
	linea_credito = CreditLine()
	linea_credito.load(linea_credito_id)
	linea_credito.delete()
	return HttpResponseRedirect(reverse('simucredito:lineas_credito', args=(admin_id,)))

def admin_credito(request, admin_id):
	if not Session().verify(admin_id):
		return HttpResponseRedirect(reverse('simucredito:login_user'))
	administrator = Administrator()
	administrator.load(admin_id)
	return render(request, "simucredito/admin_credito.html", 
		{
		"administrator": administrator
		})

def admin_credito_detalles(request, admin_id, credito_id):
	if not Session().verify(admin_id):
		return HttpResponseRedirect(reverse('simucredito:login_user'))
	administrator = Administrator()
	administrator.load(admin_id)
	credito = Credit()
	credito.load(credito_id)
	return render(request, "simucredito/admin_credito_detalles.html", {
		"administrator": administrator,
		"credito": credito,
		"paymentplans": credito.detalles
		})
		
"""Views for clients"""
def client_menu(request, admin_id):
	administrator = Administrator()
	administrator.load(admin_id)
	return render(request, "simucredito/client_menu.html", 
		{
		"administrator": administrator,
		"documenttypes": DocumentTypes(),
		})
	
def nuevo_credito(request, admin_id):
	administrator = Administrator()
	administrator.load(admin_id)
	return render(request, "simucredito/nuevo_credito.html", {
		"administrator": administrator,
		"documenttypes": DocumentTypes()
		})

def crear_credito(request, admin_id):
	cliente = Client()
	client_id = admin_id + str(request.POST["tipo_documento"]) + str(request.POST["numero_documento"])
	credit_line = CreditLine()
	credit_line.load(request.POST["linea_credito"])
	credito = Credit()
	tipo_documento = DocumentType('', '')
	if cliente.client_exists(admin_id, request.POST["tipo_documento"], request.POST["numero_documento"]):
		credito.create(admin_id, client_id, request.POST["nombres"], request.POST["apellidos"], tipo_documento.get_document_name(request.POST["tipo_documento"]), request.POST["numero_documento"], request.POST["fecha_nacimiento"], credit_line.tipo, request.POST["valor"], request.POST["cuotas"], credit_line.tasa_interes, str(datetime.datetime.now()))
	else:
		cliente.create(admin_id, request.POST["nombres"], request.POST["apellidos"], request.POST["tipo_documento"], tipo_documento.get_document_name(request.POST["tipo_documento"]), request.POST["numero_documento"], request.POST["fecha_nacimiento"])
		credito.create(admin_id, client_id, request.POST["nombres"], request.POST["apellidos"], tipo_documento.get_document_name(request.POST["tipo_documento"]), request.POST["numero_documento"], request.POST["fecha_nacimiento"], credit_line.tipo, request.POST["valor"], request.POST["cuotas"], credit_line.tasa_interes, str(datetime.datetime.now()))
	messages.add_message(request, messages.INFO, 'Se ha creado correctamente el credito')
	return HttpResponseRedirect(reverse('simucredito:client_menu', args=(admin_id,)))
	
def buscar_credito(request, admin_id):
	cliente = Client()
	if cliente.client_exists(admin_id, request.POST["tipo_documento"], request.POST["numero_documento"]):
		client_id = admin_id + str(request.POST["tipo_documento"]) + str(request.POST["numero_documento"])
		return HttpResponseRedirect(reverse('simucredito:client_credito', args=(admin_id, client_id)))
	else:
		messages.add_message(request, messages.INFO, 'Cliente no existe / No tiene creditos asociados')
		return HttpResponseRedirect(reverse('simucredito:client_menu', args=(admin_id,)))
		
def client_credito(request, admin_id, client_id):
	administrator = Administrator()
	administrator.load(admin_id)
	cliente = Client()
	cliente.load(client_id)
	return render(request, "simucredito/client_credito.html", 
		{
		"administrator": administrator,
		"cliente": cliente,
		})

def client_credito_detalles(request, admin_id, client_id, credito_id):
	administrator = Administrator()
	administrator.load(admin_id)
	cliente = Client()
	cliente.load(client_id)
	credito = Credit()
	credito.load(credito_id)
	return render(request, "simucredito/client_credito_detalles.html", {
		"administrator": administrator,
		"cliente": cliente,
		"credito": credito,
		"paymentplans": credito.detalles
		})

simucredito/templates/simucredito/admin_credito.html
{% extends "simucredito/admin_base.html" %}
{% block nombre_admin %}{{ administrator.nombres }} {{ administrator.apellidos }}{% endblock %}
{% block admin_id %}{% url "simucredito:logout_user" administrator.id %}{% endblock %}
{% block seccion %}Planes de pago{% endblock %}
{% block admin_home %}{% url "simucredito:admin_menu" administrator.id %}{% endblock %}
{% block lineas_credito %}{% url 'simucredito:lineas_credito' administrator.id %}{% endblock %}
{% block admin_credito%}{% url 'simucredito:admin_credito' administrator.id %}{% endblock %}
{% block admin_credito_estado %}class="active"{% endblock %}

{% block content %}
<div class="panel-body">
	<div class="table-responsive">
		<table class="table table-striped table-bordered table-hover">
		    <tr>
				<th>Numero documento</th>
				<th>Tipo documento</th>
				<th>Apellidos</th>
				<th>Nombres</th>
				<th>Valor credito</th>
				<th>Plazos</th>
				<th>Linea</th>
				<th>Estado</th>
				<th>Nivel riesgo</th>
				<th>Fecha creacion</th>
			</tr>
		    {% for each_credit in administrator.credits %}
		    <tr>
				<td>{{ each_credit.numero_documento_cliente }}</td>
				<td>{{ each_credit.tipo_documento_cliente }}</td>
				<td>{{ each_credit.apellidos_cliente }}</td>
				<td>{{ each_credit.nombres_cliente }}</td>
				<td>${{ each_credit.valor }}</td>
				<td>{{ each_credit.cuotas }}</td>
				<td>{{ each_credit.linea_credito }}</td>
				<td>{{ each_credit.estado }}</td>
				<td>{{ each_credit.nivel_riesgo }}</td>
				<td>{{ each_credit.fecha_creacion }}</td>
				<td><a class="btn btn-default btn-block btn-primary{% if each_credit.nivel_riesgo == "No disponible" %} disabled{% endif %}" href="{% url 'simucredito:admin_credito_detalles' administrator.id each_credit.id %}">Ver detalles</a></td>
			</tr>
		    {% endfor %}
		</table>
	</div>
</div>
{% endblock %}

simucredito/templates/simucredito/client_credito.html
{% extends "simucredito/client_base.html" %}
{% block admin_home %}{% url "simucredito:client_menu" administrator.id %}{% endblock %}
{% block nombre_admin %}{{ cliente.nombres }} {{ cliente.apellidos }}{% endblock %}
{% block seccion %}Mis creditos{% endblock %}
{% block nuevo_credito %}{% url 'simucredito:nuevo_credito' administrator.id %}{% endblock %}
{% block buscar_credito%}{% url 'simucredito:buscar_credito' administrator.id %}{% endblock %}

{% block content %}
<div class="panel-body">
	<div class="table-responsive">
		<table class="table table-striped table-bordered table-hover">
		    <tr>
				<th>Numero documento</th>
				<th>Tipo documento</th>
				<th>Apellidos</th>
				<th>Nombres</th>
				<th>Valor credito</th>
				<th>Plazos</th>
				<th>Linea</th>
				<th>Estado</th>
				<th>Nivel riesgo</th>
				<th>Fecha creacion</th>
			</tr>
		    {% for each_credit in cliente.credits %}
		    <tr>
				<td>{{ each_credit.numero_documento_cliente }}</td>
				<td>{{ each_credit.tipo_documento_cliente }}</td>
				<td>{{ each_credit.apellidos_cliente }}</td>
				<td>{{ each_credit.nombres_cliente }}</td>
				<td>${{ each_credit.valor }}</td>
				<td>{{ each_credit.cuotas }}</td>
				<td>{{ each_credit.linea_credito }}</td>
				<td>{{ each_credit.estado }}</td>
				<td>{{ each_credit.nivel_riesgo }}</td>
				<td>{{ each_credit.fecha_creacion }}</td>
				<td><a class="btn btn-default btn-block btn-primary{% if each_credit.nivel_riesgo == "No disponible" %} disabled{% endif %}" href="{% url 'simucredito:client_credito_detalles' administrator.id cliente.id each_credit.id %}">Ver detalles</a></td>
			</tr>
		    {% endfor %}
		</table>
	</div>
</div>
{% endblock %}

simucredito/templates/simucredito/linea_credito.html
{% extends "simucredito/admin_base.html" %}
{% block nombre_admin %}{{ administrator.nombres }} {{ administrator.apellidos }}{% endblock %}
{% block admin_id %}{% url "simucredito:logout_user" administrator.id %}{% endblock %}
{% block seccion %}Editar linea de credito{% endblock %}
{% block admin_home %}{% url "simucredito:admin_menu" administrator.id %}{% endblock %}
{% block lineas_credito %}{% url 'simucredito:lineas_credito' administrator.id %}{% endblock %}
{% block admin_credito%}{% url 'simucredito:admin_credito' administrator.id %}{% endblock %}
{% block lineas_credito_estado %}class="active"{% endblock %}

{% block content %}
<form action="{% url 'simucredito:editar_linea_credito' administrator.id linea_credito.id %}" method="post" id="linea_credito">
{% csrf_token %}

<div class="form-group col-lg-3">
    <label>Linea de credito: </label> {{ linea_credito.tipo }}<br>
    <label>Numero maximo de cuotas:</label> {{ linea_credito.cuotas_maximas }}<br>
    <label>Tasa de interes:</label>
    <input class="form-control" type="number" name="tasa_interes" min="0" max="9.9" step="0.1" value="{{ linea_credito.tasa_interes }}"/><br>
    <input class="btn btn-default btn-primary" type="submit" value="Editar"/>
</div>
</form>
{% endblock %}

simucredito/templates/simucredito/lineas_credito.html
{% extends "simucredito/admin_base.html" %}

{% block functions %}
<script type="text/javascript">
    function eliminarLineaCredito(credit_line, url){
        if( confirm("¿Esta seguro que desea eliminar la linea de credito \"" + credit_line + "\"?\n") ){
            var form = document.getElementById("eliminar_linea_credito");
            form.action = url;
            form.submit();
        }
    }
</script>
{% endblock %}

{% block nombre_admin %}{{ administrator.nombres }} {{ administrator.apellidos }}{% endblock %}
{% block admin_id %}{% url "simucredito:logout_user" administrator.id %}{% endblock %}
{% block seccion %}Lineas de credito{% endblock %}
{% block admin_home %}{% url "simucredito:admin_menu" administrator.id %}{% endblock %}
{% block lineas_credito %}{% url 'simucredito:lineas_credito' administrator.id %}{% endblock %}
{% block admin_credito%}{% url 'simucredito:admin_credito' administrator.id %}{% endblock %}
{% block lineas_credito_estado %}class="active"{% endblock %}

{% block content %}
<form action="" method="post" id="eliminar_linea_credito">{% csrf_token %}</form>

                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="tabla_lineas_credito">
                                    <thead>
                                        <tr>
                                            <th>Nombre</th>
                                            <th>Tasa mensual</th>
                                            <th>Fecha de creacion</th>
                                            <th>Fecha de modificacion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for each_creditline in administrator.creditlines %}
                                        <tr>
                                            <td>{{ each_creditline.tipo }}</td>
                                            <td>{{ each_creditline.tasa_interes }}%</td>
                                            <td>{{ each_creditline.fecha_creacion }}</td>
                                            <td>{{ each_creditline.fecha_modificacion }}</td>
                                            <td><a class="btn btn-default btn-block btn-primary" href="{% url 'simucredito:linea_credito' administrator.id each_creditline.id %}">Editar</a></td>
                                            <td><button class="btn btn-default btn-block btn-danger" onclick="eliminarLineaCredito('{{ each_creditline.tipo }}', '{% url 'simucredito:eliminar_linea_credito' administrator.id  each_creditline.id %}')">Eliminar</button></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->

                    <div style="bottom-marging: 100px">
                        <a class="btn btn-default btn-primary" href="{% url 'simucredito:nueva_linea_credito' administrator.id %}">Nueva</a>
                    </div>
{% endblock %}

simucredito/templates/simucredito/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>Simuladores de credito - Login</title>
        <meta name="generator" content="Bootply" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href="{% static "simucredito/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
        <!--[if lt IE 9]>
            <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link href="{% static "simucredito/login/css/styles.css" %}" rel="stylesheet">
    </head>
    <body>
    <!--login modal-->
    <div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h1 class="text-center">Login</h1>
          </div>
          <div class="modal-body">
              <form class="form col-md-12 center-block" method="post" action="{% url 'simucredito:autenticar' %}">
                {% csrf_token %}
                <div class="form-group">
                  <input type="text" class="form-control input-lg" placeholder="Email" name="usuario">
                </div>
                <div class="form-group">
                  <input type="password" class="form-control input-lg" placeholder="Password" name="password">
                </div>
                <div class="form-group">
                  <button class="btn btn-primary btn-lg btn-block">Sign In</button><br>
                  <a href="{% url "simucredito:index" %}" class="btn btn-default btn-xs pull-right">Cancelar</a>
                  <span class="pull-left"><a href="{% url "simucredito:nuevo_administrador" %}">Registro</a></span>
                </div>
              </form>
          </div>
          <div class="modal-footer">
          </div>
      </div>
      </div>
    </div>
    <!-- jQuery Version 1.11.0 -->
    <script src="{% static "simucredito/bootstrap/js/jquery-1.11.0.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "simucredito/bootstrap/js/bootstrap.min.js" %}"></script>
    </body>
</html>

simucredito/templates/simucredito/simucredito_base.html
<!DOCTYPE html>
<html>
<head>
    <title>Simuladores de credito</title>
</head>
<body>
<h1>Prueba</h1>
<p>Prueba de simuladores de credito - Template base</p>
</body>
</html>

simucredito/templates/simucredito/sqs.html
[
	{ "name" : "worker", "quantity" : {{ queue_count }} }
]